### ISSUE TITLE
Ability to return query object without running request

### ISSUE THREAD

**Issue by benjamin-glitsos** [marpple/FxSQL#3]
Hi Marpple, this is a very cool library, however I'm having a problem where all of my queries time out without running any http request. It is strange because I don't have this problem with node-postgres. Maybe you would know what is the difference there.

But anyway, as a workaround, I'm wondering if there is a way to return the query object from these library functions that is returned by FxSQL_DEBUG.LOG. For example, something like this:

``LOG(QUERY `SELECT ${"hi~"} as ho`)``

=>

`{ text: 'SELECT $1 as ho', values: ['hi'] }`

Then I would be able to use this object myself to make the request using node-postgres.

Is that possible? Thanks for your time.

**Comment by ne2030** [comment]
Hi benjamin, thanks for using our library and sorry for late reply.

First, we do not know exact problem or situations due to lack of information. Could you put any error messages or code snippets? Then, we can check detailed causes.

Second, FxSQL has 'SQL' function which returns object which you wanted.

```SQL`SELECT * FROM table WHERE name = ${'fxsql'} AND age = ${20}`() ```
=>
``` { text: 'SELECT * FROM table WHERE name = ?? AND age = ??', values: ['fxsql', 20] } ```

The variable part of text is bit different with normal query string, but i believe you can easily convert '??' to $1, $2.

**Comment by benjamin-glitsos** [comment]
Hi,

Thank you for that! I think that will solve my problem quite well.

Thank you for the support, and I really like your library.

**Comment by ne2030** [comment]
Thank you!
